spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://shorjin09:iHt1BktvwtF99eMr@user-data.yrq6sbl.mongodb.net/?retryWrites=true&w=majority&appName=user-data
      database: userdb
## connect to local mangodb
#    mongodb:
#      uri: mongodb://localhost:27017/userdb
#      database: userdb


#   connect to postgresql
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: shorjin
#    password: shorjin
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Connect to h2
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082

